language: r
cache: packages
sudo: required
warnings_are_errors: false

env:
  global:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;
  - find *Rcheck -name '00install.out' -print -exec tail -n 100 '{}' \;
  - find *Rcheck -name '00check.log' -print -exec tail -n 100 '{}' \;

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get install glpk-utils libglpk-dev

script: 
  - |
    travis_wait 30 R CMD build . --no-manual
    travis_wait  R CMD check TraME*tar.gz --no-manual
