language: r
sudo: required
warnings_are_errors: true

script:
- |
  R CMD build .
  travis_wait 40 R CMD check TraME.Rcpp*.tar.gz

env:
  global:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
