language: r
cache: packages
sudo: required
warnings_are_errors: false

env:
  global:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

script: 
  - |
    travis_wait 20 R CMD build . --no-manual
    travis_wait  R CMD check TraME*tar.gz --no-manual
